[project]
name = "dsa-templates"
version = "0.1.0"
description = "Collection of data structures and algos in Python3 and Rust"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "sphinx>=7.2.0",
    "sphinx-rtd-theme",
    "sphinx-copybutton",
]
